### ISSUE TITLE
Not necessarily an issue - appears to have run and terminated normally but no output/index.html

### ISSUE THREAD

**Issue by slash-dot** [raghur/TomatoKetchup#3]
Can you tell if I am just looking for it in the wrong place?  I looked in the TomatoKetchup directory.  If not, any idea what might be wrong or if there is a log file in which I might find out why I never got the output/index.html

Thanks a lot for making this btw.  I have never cleared my Tomato routers' NVRAM since I began running it but I am almost out of NVRAM storage now.  I always wanted to figure out how to restore the settings using this utility.

**Comment by raghur** [comment]
sorry - very little to go on here... perhaps check if you happened to save the file somewhere else or gave a diff path...

**Comment by mikerogerz** [comment]
I get the same issue as @raghur reported. I've tried setting the output for different locations (a tmp dir, current dir, multiple locations). No error at all, just finishes and no output file is generated.

Also don't see any way to show verbose output (to see any possible warnings/errors).
